### PR TITLE
KernelManager: Fix language detection

### LINKED ISSUE #696: IJavascript not detected by Atom on Mac
**Description:**
IJavascript not detected by Atom on Mac

**Steps to Reproduce:**

1. Install Hyderogen
2. Install IJavaScript
3. OPen atom and do Hydrogen: update

**Versions:**

Which OS and which version of Hydrogen and Atom are you running?
Mac - 10.12.3
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Hydrogen: 1.10.0

You can get this information from copy and pasting the output of `atom --version`  from the command line.

**Logs:**

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md).

### PR DESCRIPTION
**Pull request by n-riesco**
* Use lowercase in language name comparisons

* Ensured that `grammarToLanguage(grammar)` returns the mapped language.

Fixes #696

### CODE REVIEW

**Comment by n-riesco** [comment]
Oh! I thought the plan was to use grammar language names instead of kernel language names.

File: lib/utils.js [hunk 1]
```diff
@@ -36,7 +36,9 @@ export function grammarToLanguage(grammar: ?atom$Grammar) {
     l => l.toLowerCase() === grammarLanguage
   );
 
-  return kernelLanguage ? kernelLanguage.toLowerCase() : grammarLanguage;
```
Comment (lgeiger) [inline lib/utils.js]: [`_.findKey`](https://lodash.com/docs/4.17.4#findKey) already returns the mapped language.

Comment (lgeiger) [inline lib/utils.js]: So I think this line can remain unchanged

Comment (n-riesco) [inline lib/utils.js]: The way I understood `languageMappings` is that if it was set to `{ "babel": "javascript"}`, then a kernel that declares it can run `babel`, will be regarded by Hydrogen as a kernel that can run `javascript`.

Comment (n-riesco) [inline lib/utils.js]: I'm going to update the spec for `grammarToLanguage` so you can see what I mean.

Comment (n-riesco) [inline lib/utils.js]: Oh! I see my confusion. Since we are mapping by kernel names, we need to return the kernel name!

Comment (n-riesco) [inline lib/utils.js]: I'm chasing another bug; even with this PR `{ "babel": "javascript"}` doesn't work.

**Comment by n-riesco** [comment]
@lgeiger I've noticed that I need to close and open Atom for change in `kernelSpec` to take effect.

Shall I open an issue?

**Comment by lgeiger** [comment]
Sorry, I wasn't able to help earlier, glad you figured it out 👍 

> I'm chasing another bug; even with this PR `{ "babel": "javascript"}` doesn't work.

You're right the language mappings are confusing, but we can't change the behavior since it would break all existing configs and cause even more confusion 😄 
I tried to improve the [documentation](https://github.com/nteract/hydrogen/blob/master/lib/config.js#L55) in my last PR to make it clearer.

> I've noticed that I need to close and open Atom for changes in kernelSpec to take effect.

You should be able to run "Hydrogen: Update Kernels" to trigger a update. Is it broken?
If you like, you can chime in on #35 for automatically detecting kernel spec changes.
