### PR TITLE
Drop Support For Re-evaluating Bubbles

### LINKED ISSUE #1474: Documentation of Bubbles
**Description:**

Bubbles aren't documented anywhere that I can find. After a couple hours of trying to find more information, I just figured it was something only existing users might know about.

### LINKED ISSUE #1516: Hydrogen Restart Kernel throws error message
Hello everyone, 

First of all, many thanks to the Hydrogen developers, it's a great tool.
I'm having trouble when I restart my python kernel from the command palette. Apparently it's not a known issue yet so below is the error report I get. It's not blocking, but I currently have to restart Atom to get it to work properly.

Thanks again, 

Francisco

********** HYDROGEN ERRROR REPORT **********

[Enter steps to reproduce:]

1. Control+ P (Command Palette)
2. Hydrogen: Restart Kernel and Re-evaluate bubbles

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Windows 7
**Thrown From**: [Hydrogen](ssh://git@github.com/nteract/hydrogen) package 2.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At C:\Users\F_REYZALUAR\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'match' of undefined
    at TextEditor.isBufferRowCommented (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:44757)
    at isBlank (/packages/Hydrogen/lib/code-manager.js:64:55)
    at Object.escapeBlankRows (/packages/Hydrogen/lib/code-manager.js:73:10)
    at /packages/Hydrogen/lib/main.js:490:36)
    at /packages/Hydrogen/lib/main.js:492:8
    at arrayEach (/packages/Hydrogen/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/packages/Hydrogen/node_modules/lodash/lodash.js:9344:14)
    at Object._runAll (/packages/Hydrogen/lib/main.js:486:7)
    at Object.runAll (/packages/Hydrogen/lib/main.js:466:12)
    at /packages/Hydrogen/lib/main.js:411:33
    at /packages/Hydrogen/lib/zmq-kernel.js:203:24
    at ZMQKernel.onConnect (/packages/Hydrogen/lib/zmq-kernel.js:127:21)
    at emitThree (events.js:141:20)
    at Socket.emit (events.js:217:7)
    at Object.self._zmq.onMonitorEvent (/packages/Hydrogen/node_modules/zeromq/lib/index.js:552:12)
```

### Commands

```
     -2:32.6.0 hydrogen:run (input.hidden-input)
     -2:32.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -1:11.2.0 core:backspace (input.hidden-input)
     -1:10.1.0 intentions:highlight (input.hidden-input)
     -1:09.9.0 core:save (input.hidden-input)
     -1:06.7.0 intentions:highlight (input.hidden-input)
     -1:06.4.0 command-palette:toggle (input.hidden-input)
     -1:02.9.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:02.7.0 core:backspace (input.hidden-input)
     -1:01.4.0 intentions:highlight (input.hidden-input)
  2x -1:01.1.0 command-palette:toggle (input.hidden-input)
     -0:50 intentions:highlight (input.hidden-input)
     -0:49.5.0 command-palette:toggle (input.hidden-input)
     -0:47.3.0 core:move-down (input.hidden-input)
     -0:47.1.0 core:confirm (input.hidden-input)
     -0:47.1.0 hydrogen:restart-kernel-and-re-evaluate-bubbles (input.hidden-input)
```

### Non-Core Packages

```
atom-file-icons 0.6.0 
atom-language-r 1.4.8 
atom-material-ui 2.1.3 
autocomplete-python 1.11.0 
autocomplete-R 0.6.0 
busy-signal 2.0.0 
goto-definition 1.3.4 
Hydrogen 2.7.0 
hydrogen-launcher 1.2.2 
ide-r 0.1.8 
intentions 1.1.5 
kite 0.140.0 
linter 2.3.0 
linter-flake8 2.4.0 
linter-lintr 1.1.4 
linter-ui-default 1.7.1 
minimap 4.29.9 
platformio-ide-terminal 2.8.4 
rbox 0.5.0 
script 3.18.1 
```

### PR DESCRIPTION
**Pull request by wadethestealth**
# Why:
The feature seems to not work very friendly with cells, and has had a long standing bug because of this.
The feature itself would be difficult to implement properly with very little benefit.
We currently support watches which accomplish most of the need for this feature.
IMO: If you wanted to re-evaluate bubbles, you should do so on a bubble by bubble basis since you should want to avoid re-evaluating long or unrelated tasks.

See #861 to understand why the feature was creating originally

---

- Closes #1516
- Closes #1474

### CODE REVIEW

**Comment by BenRussert** [comment]
I support this PR and will take a look at if there is any other code we can :fire: along with the command in main. I think  we should leave this open a few days to give people a chance to see.

If anyone wants to keep this feature that is great, but we will need you to own its maintenance almost entirely. I don't have a great understanding of the features requirements of the command or how to explain them to new users and maintainers, so I think it is better to drop support unless someone can take responsibility for it.

File: lib/main.js [hunk 1]
```diff
@@ -420,23 +418,6 @@ const Hydrogen = {
...
-    markers.clear();
-
-    if (!editor || !kernel) {
-      this.runAll(breakpoints);
-    } else {
-      kernel.restart(() => this.runAll(breakpoints));
-    }
-  },
-
   toggleBubble() {
```
Comment (aviatesk) [inline lib/main.js]: I believe `toggleBubble` is only used for the command, thus you should drop this as well.
(Plz make a double check)

Comment (wadethestealth) [reply lib/main.js]: `toggleBubble` is a separate feature

Comment (aviatesk) [reply lib/main.js]: Ah really ? Plz explain the usage.

Comment (aviatesk) [reply lib/main.js]: Refer to this: https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html#hydrogen-toggle-bubble

**Comment by wadethestealth** [comment]
@aviatesk Thanks for the catch. I have temporarily refactored `toggleBubble` to `clearBubble` which could be used to remove one bubble or many within a selection which was a feature of `toggleBubble`

File: lib/main.js (hunk 1 above)
Comment (wadethestealth) [reply lib/main.js]: It was also used for clearing bubbles singularly and not all at once. I have temporarily refactored toggleBubble to clearBubble which could be used to remove one bubble or many within a selection which was a feature of toggleBubble

**Comment by wadethestealth** [comment]
@aviatesk agreed. Also seems like I didnt look hard enough for related code. Thanks for the help.

**Comment by BenRussert** [comment]
I'm going to merge this since the active contributors seem to agree that while probably a nice feature, it is difficult to maintain while adding new cell-centric features. 

Side note: If you are someone who wants this feature to remain, please volunteer to maintain it and we can consider adding it again.
