### PR TITLE
Fix #1603

### LINKED ISSUE #1603: Uncaught TypeError: Cannot read property 'get' of undefined
[Enter steps to reproduce:]

1. Shutdown python3.6.6 kernel in virtual environment.

**Atom**: 1.36.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 2.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'get' of undefined

```
At C:\Users\*******\.atom\packages\Hydrogen\lib\store\index.js:175

TypeError: Cannot read property 'get' of undefined
    at /packages/Hydrogen/lib/store/index.js:175:23
    at Array.filter (<anonymous>)
    at Store.getFilesForKernel (/packages/Hydrogen/lib/store/index.js:171:27)
    at Store.deleteKernel (/packages/Hydrogen/lib/store/index.js:154:24)
    at /packages/Hydrogen/node_modules/mobx/lib/mobx.js:604:22)
    at Store.res (/packages/Hydrogen/node_modules/mobx/lib/mobx.js:595:16)
    at Kernel.destroy (/packages/Hydrogen/lib/kernel.js:399:11)
    at /packages/Hydrogen/lib/main.js:334:14)
    at Object.handleKernelCommand (/packages/Hydrogen/lib/main.js:344:4)
    at SignalListView.signalListView.onConfirmed (/packages/Hydrogen/lib/main.js:292:14)
    at Object.didConfirmSelection (/packages/Hydrogen/lib/signal-list-view.js:40:36)
    at SelectListView.confirmSelection (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:400:20)
    at SelectListView.didClickItem (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:286:10)
    at ListItemView.onclick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:221:31)
    at ListItemView.didClick (/packages/Hydrogen/node_modules/atom-select-list/src/select-list-view.js:448:10)
```

### Commands

```
     -3:13.7.0 core:backspace (input.hidden-input)
     -3:13.1.0 core:move-down (input.hidden-input)
     -3:12.9.0 core:move-right (input.hidden-input)
     -3:12.6.0 core:backspace (input.hidden-input)
     -3:12 core:save (input.hidden-input)
  6x -3:11.1.0 editor:move-to-end-of-word (input.hidden-input)
     -3:09.6.0 editor:newline (input.hidden-input)
     -3:09.2.0 core:save (input.hidden-input)
     -3:06.4.0 hydrogen:run (input.hidden-input)
     -3:06.4.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.has-selection)
     -2:49 editor:newline (input.hidden-input)
     -2:47.2.0 core:save (input.hidden-input)
     -2:46.6.0 core:select-all (input.hidden-input)
     -0:56.5.0 application:new-file (input.hidden-input)
     -0:54.8.0 core:paste (input.hidden-input)
  2x -0:53.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-virtualenv 1.0.2 
block-select 1.0.0 
git-plus 8.6.2 
goto-definition 1.3.4 
Hydrogen 2.9.0 
kite 0.156.0 
```

### PR DESCRIPTION
**Pull request by aviatesk**
## Purpose of this PR:

Fixes #1603

## Desc

I found this issue is basically caused by this part: https://github.com/nteract/hydrogen/blob/2d53a2554b37ad02e09981a77e36131e1cd46ed8/lib/main.js#L199

In short, if a file within which a kernel got already destroyed gets renamed, this part in `forceEditorUpdate` change `kernelMapping` into funny state:
https://github.com/aviatesk/hydrogen/blob/432850814ae573e6da95ca75e8a75c6ad4e68840/lib/store/index.js#L248

Addressed by making a part within `forceEditorUpdate` to check whether the map has the file or not and return if not.

## Misc

This PR also contains some modifications for kernel-monitor.js and .js.flow files:
- Name stateless anonymous function to show kernelspec button (kernel-monitor.js)
- Add flow annotations for .js.flow files (eslint-flow-plugin complains otherwise)

### CODE REVIEW

File: types/hydrogen.js.flow [hunk 1]
```diff
@@ -1,3 +1,5 @@
+/* @flow */
```
Comment (BenRussert) [inline types/hydrogen.js.flow]: A long time ago I had this issue where I could not get hydrogen to load or test to run. I spent all sorts of time looking into it and reinstalled atom even. It turned out that I was using `// @flow` instead of `/* @flow */` or other way around and atom only supported one of the two. So we should be consistent with the one we use in all files

Mainly commenting so you don't have the same issue sometime (maybe atom fixed this)

Comment (aviatesk) [reply types/hydrogen.js.flow]: Thanks for telling me your experience, it must be so annoying 😅 
Maybe the recent version of Atom already fixed this, but anyway I would fix them.
