### PR TITLE
Fix restarting kernels connected via `connection.json` (issue #394)

### LINKED ISSUE #394: Restarting kernels connected via `connection.json` is broken

### PR DESCRIPTION
**Pull request by n-riesco**
Fixes #394

### CODE REVIEW

File: lib/zmq-kernel.coffee [hunk 1]
```diff
@@ -17,12 +17,11 @@ class ZMQKernel extends Kernel
 
         @executionCallbacks = {}
 
-        projectPath = path.dirname(
```
Comment (n-riesco) [inline lib/zmq-kernel.coffee]: leftover from #391

**Comment by lgeiger** [comment]
This still isn't working for me. If I connect to an existing kernel and use the menu to restart it, I still get an error ([here](https://github.com/nteract/hydrogen/blob/master/lib/main.coffee#L200)) because the kernel can't be restarted.
I'm currently away the next two weeks so won't be able to fix this issue.

File: lib/zmq-kernel.coffee [hunk 2]
```diff
@@ -44,15 +43,16 @@ class ZMQKernel extends Kernel
...
+                console.log 'ZMQKernel: stderr:', data
 
                 regexp = getKernelNotificationsRegExp()
                 if regexp?.test data
                     atom.notifications.addError @kernelSpec.display_name,
                         detail: data, dismissable: true
         else
-            atom.notifications.addInfo 'Using custom kernel connection:',
-                detail: @connectionFile
+            console.log 'ZMQKernel: connectionFile:', connectionFile
```
Comment (lgeiger) [inline lib/zmq-kernel.coffee]: This is working but shouln't it be `@connectionFile`?

File: lib/zmq-kernel.coffee [hunk 3]
```diff
@@ -93,15 +93,24 @@ class ZMQKernel extends Kernel
...
+            console.log 'ZMQKernel: cannot interrupt an existing kernel'
+            atom.notifications.addWarning 'Cannot interrupt this kernel'
+
+
+    shutdown: (restart) ->
+        requestId = 'shutdown_' + uuid.v4()
+        message = @_createMessage 'shutdown_request', requestId
+
+        message.content =
+            restart: not not restart
```
Comment (lgeiger) [inline lib/zmq-kernel.coffee]: Why aren't you using a default value in the function definition?

File: lib/zmq-kernel.coffee [hunk 4]
```diff
@@ -306,30 +320,27 @@ class ZMQKernel extends Kernel
...
-        console.log 'sending shutdown'
+        console.log 'ZMQKernel: destroy:', this
 
-        message = @_createMessage 'shutdown_request'
-        message.content =
-            restart: false
-
-        @shellSocket.send new jmp.Message message
+        if @kernelProcess?
+            @interrupt()
```
Comment (lgeiger) [inline lib/zmq-kernel.coffee]: Is sending `@kernelProcess.kill 'SIGINT'` working correctly? Before we were using `@kernelProcess.kill 'SIGKILL'`.

File: lib/zmq-kernel.coffee [hunk 5]
```diff
@@ -306,30 +320,27 @@ class ZMQKernel extends Kernel
...
+            fs.unlink @connectionFile
+        else
+            @shutdown()
```
Comment (lgeiger) [inline lib/zmq-kernel.coffee]: I think we should send an shutdown message even if `@kernelProcess` is defined.

File: lib/zmq-kernel.coffee [hunk 6]
```diff
@@ -306,30 +320,27 @@ class ZMQKernel extends Kernel
...
 
         @shellSocket.close()
+        @controlSocket.close()
         @ioSocket.close()
+        @stdinSocket.close()
```
Comment (lgeiger) [inline lib/zmq-kernel.coffee]: 👍

File: lib/zmq-kernel.coffee (hunk 4 above)
Comment (n-riesco) [inline lib/zmq-kernel.coffee]: Good catch, `SIGINT` is for interrupting the kernel and `SIGKILL` is to kill it.

**Comment by n-riesco** [comment]
We should create a label for `late-night-PR-review-with-care`. :disappointed:

**Comment by lgeiger** [comment]
> We should create a label for `late-night-PR-review-with-care`. 😞

😄 😄 👍

**Comment by rgbkrk** [comment]
We're sitting on 67 commits since the last release, do you think we'll be shipping a new version soon, possibly with this PR?

**Comment by n-riesco** [comment]
[WIP] Not ready for merging

**Comment by n-riesco** [comment]
PR is ready for review/merging.

File: lib/kernel-manager.coffee [hunk 7]
```diff
@@ -35,6 +36,24 @@ class KernelManager
...
+            kernel.restart().then -> onRestarted?(kernel)
+            return
+
+        if kernel instanceof ZMQKernel and kernel.kernelProcess
+            kernelSpec = kernel.kernelSpec
+            @destroyRunningKernelFor grammar
+            @startKernel kernelSpec, grammar, (kernel) -> onRestarted?(kernel)
+            return
+
+        console.log 'KernelManager: restartRunningKernelFor: ignored', kernel
```
Comment (lgeiger) [inline lib/kernel-manager.coffee]: I think we should add an atom notification here.

File: lib/zmq-kernel.coffee [hunk 8]
```diff
@@ -306,30 +329,27 @@ class ZMQKernel extends Kernel
 
 
     destroy: ->
```
Comment (lgeiger) [inline lib/zmq-kernel.coffee]: I think we should add the `restart` option from `@shutdown`.

Comment (n-riesco) [inline lib/zmq-kernel.coffee]: On 07/08/16 08:40, Lukas Geiger wrote:
> In lib/zmq-kernel.coffee <https://github.com/nteract/hydrogen/pull/396#discussion_r73797331>:
> 
>> @@ -306,30 +329,27 @@ class ZMQKernel extends Kernel
>>  
>>  
>>      destroy: ->
> 
> I think we should add the |restart| option from |@shutdown|.

I'd find this confusing. Because of its name, `destroy` makes me think that we expect it be used as a class destructor.

I wouldn't expect a class instance to be usable after invoking its destructor (and so, the restart option wouldn't make sense).

Do we have any use for `destroy(restart)`?

Comment (lgeiger) [inline lib/zmq-kernel.coffee]: OK I see, it makes sense.
I was just wondering because `@shutdown` has an restart option which isn't used anywhere. But this can be left for an future PR.

**Comment by lgeiger** [comment]
Thanks for this great PR! (And sorry for the late reply)

File: lib/zmq-kernel.coffee (hunk 8 above)
Comment (n-riesco) [inline lib/zmq-kernel.coffee]: Unfortunately, the use of the `shutdown` message is undermined by frontends like the notebook. When the notebook restarts a kernel, what actually happens is that the notebook kills the kernel process and an relaunches a new kernel.

Judging by [this proposal](https://github.com/jupyter/enhancement-proposals/pull/14), this behaviour won't change in the future.
