### PR TITLE
Fix #477

### LINKED ISSUE #477: Cannot read property 'trim' of undefined
Hi all,

attempting to run a block of Python code broken over several lines, e.g.
```
print([p for p in 
    [0,1,2,3]])
```
having the cursor on the first line of the block sometimes (really, sometimes not) results in the following:

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package, v0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'trim' of undefined

```
At /C:/Users/HSG-Spezial/.atom/packages/Hydrogen/lib/code-manager.coffee:88

TypeError: Cannot read property 'trim' of undefined
    at CodeManager.module.exports.CodeManager.getFoldRange (file:///C:/Users/HSG-Spezial/.atom/packages/Hydrogen/lib/code-manager.coffee:78:33)
    at CodeManager.module.exports.CodeManager.getFoldContents (file:///C:/Users/HSG-Spezial/.atom/packages/Hydrogen/lib/code-manager.coffee:86:18)
    at CodeManager.module.exports.CodeManager.findCodeBlock (file:///C:/Users/HSG-Spezial/.atom/packages/Hydrogen/lib/code-manager.coffee:35:21)
    at Object.module.exports.Hydrogen.run (file:///C:/Users/HSG-Spezial/.atom/packages/Hydrogen/lib/main.coffee:302:34)
    at atom-text-editor.subscriptions.add.atom.commands.add.hydrogen:run (file:///C:/Users/HSG-Spezial/.atom/packages/Hydrogen/lib/main.coffee:51:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\HSG-Spezial\AppData\Local\atom\app-1.11.1\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\HSG-Spezial\AppData\Local\atom\app-1.11.1\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\HSG-Spezial\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\HSG-Spezial\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\HSG-Spezial\AppData\Local\atom\app-1.11.1\resources\app.asar\src\window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (C:\Users\HSG-Spezial\AppData\Local\atom\app-1.11.1\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:20.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:19.3.0 hydrogen:clear-results (atom-text-editor.editor.is-focused)
     -0:17.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:15.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:13.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.9.0 hydrogen:run (atom-text-editor.editor.is-focused)
     -0:10.6.0 hydrogen:clear-results (atom-text-editor.editor.is-focused)
     -0:10.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:09.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:09.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:09.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:09.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.1.0 hydrogen:run (atom-text-editor.editor.is-focused)
     -0:04.1.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "ink",
      "julia-client",
      "language-julia"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "limited"
  },
  "Hydrogen": {
    "autocomplete": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.8.6 (active)
highlight-selected, v0.11.2 (active)
Hydrogen, v0.14.0 (active)
ink, v0.5.3 (inactive)
julia-client, v0.5.6 (inactive)
language-julia, v0.8.0 (inactive)
linter, v1.11.18 (active)
minimap, v4.25.0 (active)
minimap-highlight-selected, v4.4.0 (active)
project-manager, v3.2.3 (active)
script, v3.10.1 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
solarized-seti-ui, v0.8.6 (inactive)
todo-show, v1.7.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

Would much appreciate your help.

Best,

Igor

### PR DESCRIPTION
**Pull request by lgeiger**
Fix #477

### CODE REVIEW

File: lib/code-manager.coffee [hunk 1]
```diff
@@ -81,12 +81,13 @@ class CodeManager
...
     normalizeString: (code) ->
-        return code.replace /\r\n|\r/g, '\n'
+        if code?
+            return code.replace /\r\n|\r/g, '\n'
 
 
     getFoldRange: (row) ->
         range = @editor.languageMode.rowRangeForCodeFoldAtBufferRow(row)
-        if @getRow(range[1] + 1).trim() is 'end'
+        if @getRow(range[1] + 1)?.trim() is 'end'
```
Comment (rgbkrk) [inline lib/code-manager.coffee]: You can really apply the `.trim()` after the `?` operator in coffeescript? Crazy.

Comment (rgbkrk) [inline lib/code-manager.coffee]: Wowsers.
